rlm_otp: Fix key size calculation
Take size of key array element, instead of an expression attempting to
calculate the key size, in otp_gen_state().

This makes the HMAC use the full key, instead of just 4 first bytes,
increasing key strength.

This also fixes the following Coverity error:

Error: BAD_SIZEOF (CWE-467):
freeradius-server-2.2.6/src/modules/rlm_otp/otp_radstate.c:100: bad_sizeof: Taking the size of arithmetic expression "key[0] * 16" is suspicious.
freeradius-server-2.2.6/src/modules/rlm_otp/otp_radstate.c:100: remediation: Did you intend "sizeof (key[0]) * 16"?