rlm_python: Some functions were deprecated in lib >= 3.11
It fixes the below warnings:

CC src/modules/rlm_python/rlm_python.c
src/modules/rlm_python/rlm_python.c:882:2: error: 'PySys_SetPath' is deprecated [-Werror,-Wdeprecated-declarations]
        PySys_SetPath(wide_path);
        ^
/usr/include/python3.11/sysmodule.h:15:1: note: 'PySys_SetPath' has been explicitly marked deprecated here
Py_DEPRECATED(3.11) PyAPI_FUNC(void) PySys_SetPath(const wchar_t *);
^
/usr/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
                                                     ^
src/modules/rlm_python/rlm_python.c:1109:3: error: 'Py_SetProgramName' is deprecated [-Werror,-Wdeprecated-declarations]
                Py_SetProgramName(wide_name);           /* The value of argv[0] as a wide char string */
                ^
/usr/include/python3.11/pylifecycle.h:37:1: note: 'Py_SetProgramName' has been explicitly marked deprecated here
Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetProgramName(const wchar_t *);
^
/usr/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
                                                     ^
2 errors generated.
make: *** [scripts/boiler.mk:737: build/objs/src/modules/rlm_python/rlm_python.lo] Error 1