xlat_func_subst: do not add an additional self-reference
Fixes the following talloc error when %(subst) is used:

ERROR: talloc_free with references at src/lib/util/value.c:3425

        reference at src/lib/util/value.c:3982