Fix undeclared variable when compiling with TLS + without DHCP
When compiling without DHCP support but with TLS support compile
fails due to an undeclared variable in modules.c

src/main/modules.c:1386:3: error: ‘da’ undeclared

Modify variable declaration to be included based on WITH_TLS flag
as well as WITH_DHCP