small fixup as cannot have diagnostic in function
# make
CC src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c
src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c: In function
‘fb_error’:
src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c:112: error:
#pragma GCC diagnostic not allowed inside functions
src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c:113: warning:
‘isc_interprete’ is deprecated (declared at /usr/include/ibase.h:787)
src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c:114: error:
#pragma GCC diagnostic not allowed inside functions
src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c:117: error:
#pragma GCC diagnostic not allowed inside functions
src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c:118: warning:
‘isc_interprete’ is deprecated (declared at /usr/include/ibase.h:787)
src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c:119: error:
#pragma GCC diagnostic not allowed inside functions
make: ***
[build/objs/src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.lo]
Error 1