Fix undeclared variable when compiling with TLS but without DHCP and without VMPS
When compiling without DHCP and without VMPS but with TLS support
compile fails due to an undeclared variable in modules.c

src/main/modules.c:1387:3: error: 'subcs' undeclared

Modify variable declaration to be included based on WITH_TLS flag as
well as WITH_DHCP and WITH_VMPS

Fixes #4261